import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className='px-1 py-0'>
      <Head>
        <title >Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-[100vh] py-16 flex flex-col justify-center items-center'>
        <h1 className='m-0  md:leading-5 text-[4rem] text-center'>
          Welcome to <a
            className='no-underline text-sky-500 hover:underline focus:underline active:underline'
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className='mx-0 my-6 text-2xl text-center md:my-12 md:leading-5'>
          Get started by editing{' '}
          <code className={`rounded-md p-3 text-[1.1rem] bg-primary text-white`}>pages/index.tsx</code>
        </p>

        <div className='flex flex-wrap items-center justify-center max-w-[50rem]'>

          <a
            href="https://nextjs.org/docs"
            className='max-w-xs p-6 m-4 border shadow card hover:border-sky-500 hover:text-sky-500'>
            <div className="card-body">
              <h2 className='card-title'>Documentation &rarr;</h2>
              <p className='m-0 text-lg'>Find in-depth information about Next.js features and API.</p>
            </div>
          </a>

          <a href="https://nextjs.org/learn" className='max-w-xs p-6 m-4 border shadow card hover:border-sky-500 hover:text-sky-500'>
            <div className="card-body">
              <h2 className='card-title'>Learn &rarr;</h2>
              <p className='m-0 text-lg'>Learn about Next.js in an interactive course with quizzes!</p>
            </div>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className='max-w-xs p-6 m-4 border shadow card hover:border-sky-500 hover:text-sky-500'
          >
            <div className="card-body">
              <h2 className='card-title'>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </div>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className='max-w-xs p-6 m-4 border shadow card hover:border-sky-500 hover:text-sky-500'
          >
            <div className="card-body">
              <h2 className='card-title'>Deploy &rarr;</h2>
              <p className='m-0 text-lg'>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </div>
          </a>

          <a
            href="https://tailwindcss.com"
            className='max-w-xs p-6 m-4 border shadow card hover:border-sky-500 hover:text-sky-500'
          >
            <div className="card-body">
              <h2 className='card-title'>Tailwindcss &rarr;</h2>
              <p className='m-0 text-lg'>
                Rapidly build modern websites without ever leaving your HTML.
              </p>
            </div>
          </a>

          <a
            href="https://daisyui.com"
            className='max-w-xs p-6 m-4 border shadow card hover:border-sky-500 hover:text-sky-500'
          >
            <div className="card-body">
              <h2 className='card-title'>daisyUI &rarr;</h2>
              <p className='m-0 text-lg'>
                Your HTML doesn't need to be messy. daisyUI adds component classes to Tailwind CSS.
              </p>
            </div>
          </a>

        </div>
      </main>

      <footer className='flex items-center justify-center flex-1 p-8 border-t'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className='flex items-center justify-center flex-grow'
        >
          Powered by{' '}
          <span className='min-h-[1rem] ml-2'>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
